# Generated by Django 2.0.13 on 2020-07-08 06:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hyperstudy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Make_problem',
            new_name='Problems',
        ),
    ]
