# Generated by Django 2.0.13 on 2020-07-08 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hyperstudy', '0002_auto_20200708_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_no', models.IntegerField()),
                ('tag_UK', models.CharField(max_length=200)),
                ('response', models.TextField()),
                ('correct', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='solve_problem',
            name='author',
        ),
        migrations.DeleteModel(
            name='Solve_problem',
        ),
    ]
