# Generated by Django 2.0.13 on 2020-07-09 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyperstudy', '0003_auto_20200708_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_logs',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
